services:
  mysql2:
    image: mysql:8.0
    container_name: tioj-db
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql2_data:/var/lib/mysql
      - /var/run/mysqld:/var/run/mysqld
    restart: unless-stopped

volumes:
  mysql2_data:
